//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDataManipulatie_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtletiekInfoEntities : DbContext
    {
        public AtletiekInfoEntities()
            : base("name=AtletiekInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> tblCategorie { get; set; }
        public virtual DbSet<Club> tblClub { get; set; }
        public virtual DbSet<Persoon> tblPersoon { get; set; }
        public virtual DbSet<PersoonClub> tblPersoonClub { get; set; }
        public virtual DbSet<Proef> tblProef { get; set; }
        public virtual DbSet<ProefCategorie> tblProefCategorie { get; set; }
        public virtual DbSet<Resultaat> tblResultaat { get; set; }
        public virtual DbSet<WedstijdProef> tblWedstijdProef { get; set; }
        public virtual DbSet<Wedstrijd> tblWedstrijd { get; set; }
        public virtual DbSet<Provincie> tblProvincies { get; set; }
        public virtual DbSet<Relatie> tblRelaties { get; set; }
    }
}
