//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDataManipulatie_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoonClub
    {
        public int Id { get; set; }
        public int persoonId { get; set; }
        public string borstNummer { get; set; }
        public System.DateTime begin { get; set; }
        public Nullable<System.DateTime> eind { get; set; }
        public int clubId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Persoon Persoon { get; set; }
    }
}
