//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDataManipulatie_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProefCategorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProefCategorie()
        {
            this.WedstijdProef = new HashSet<WedstijdProef>();
        }
    
        public int Id { get; set; }
        public int proefId { get; set; }
        public int categorieId { get; set; }
        public string geslacht { get; set; }
        public string info { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Proef Proef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WedstijdProef> WedstijdProef { get; set; }
    }
}
