//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDataManipulatie_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatie
    {
        public int Id { get; set; }
        public int PersoonEenId { get; set; }
        public int PersoonTweeId { get; set; }
        public bool Geaccepteerd { get; set; }
    
        public virtual Persoon Persoon1 { get; set; }
        public virtual Persoon Persoon2 { get; set; }
    }
}
