//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDataManipulatie_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultaat
    {
        public int Id { get; set; }
        public int wedstrijdProefId { get; set; }
        public int persoonId { get; set; }
        public string plaats { get; set; }
        public string prestatie { get; set; }
        public double wind { get; set; }
    
        public virtual Persoon Persoon { get; set; }
        public virtual WedstijdProef WedstijdProef { get; set; }
    }
}
