//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDataManipulatie_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wedstrijd()
        {
            this.WedstijdProeven = new HashSet<WedstijdProef>();
        }
    
        public int Id { get; set; }
        public int clubId { get; set; }
        public System.DateTime datum { get; set; }
        public string naam { get; set; }
        public string plaats { get; set; }
    
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WedstijdProef> WedstijdProeven { get; set; }
    }
}
